### ISSUE TITLE
The average precision and recall is low

### ISSUE THREAD

**Issue by xscjun** [stefanopini/simple-HRNet#31] opened 2019-10-31 07:07 UTC
I tried continuing the training for a couple of epochs starting from official weights pose_hrnet_w32_256x192.pth. But the average precision and recall is so low：

Train AP/AR
WARNING:root:json-tricks: numpy scalar serialization is experimental and may work differently in future versions
Loading and preparing results...
DONE (t=8.20s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *keypoints*
DONE (t=78.57s).
Accumulating evaluation results...
DONE (t=2.16s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] = 0.018
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets= 20 ] = 0.041
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets= 20 ] = 0.012
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = 0.015
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] = 0.017
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] = 0.037
 Average Recall     (AR) @[ IoU=0.50      | area=   all | maxDets= 20 ] = 0.106
 Average Recall     (AR) @[ IoU=0.75      | area=   all | maxDets= 20 ] = 0.020
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = 0.035
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] = 0.039
Validating: 100%|███████████████████████████████████████████████████████████████████| 397/397 [03:31<00:00,  1.90it/s]

Val AP/AR
Loading and preparing results...
DONE (t=0.33s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *keypoints*
DONE (t=3.29s).
Accumulating evaluation results...
DONE (t=0.08s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] = 0.067
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets= 20 ] = 0.259
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets= 20 ] = 0.010
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = 0.075
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] = 0.064
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] = 0.117
 Average Recall     (AR) @[ IoU=0.50      | area=   all | maxDets= 20 ] = 0.360
 Average Recall     (AR) @[ IoU=0.75      | area=   all | maxDets= 20 ] = 0.046
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = 0.118
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] = 0.116
best_loss 0.001845 at epoch 10
best_acc 0.363634 at epoch 10
best_mAP 0.067391 at epoch 10

I continue the training with coco dataset, and load the weights pose_hrnet_w32_256x192.pth. 
I'm confused , is this result normal ? ?

**Comment by stefanopini** [comment] 2019-11-01 10:33
Duplicate of issues #26 and #29, please refer to those issues.

**Closed by stefanopini** 2019-11-01 10:33 UTC
